#%RAML 0.8
---
title: Sphinx REST API
baseUri: http://localhost:9999/{version}
version: v1
mediaType: application/json
protocols: [HTTP]

schemas:
  - Solution: !include schema/solution.json
  - Solutions: !include schema/solutions.json
  - SolutionCreateResponse: !include schema/solution_create_response.json
  - CompilerOutput: !include schema/compiler_output.json
  - Testcases: !include schema/testcases.json
  - Testcase: !include schema/testcase.json
  - TestcaseCreateResponse: !include schema/testcase_create_response.json
  - Tests: !include schema/tests.json
  - Test: !include schema/test.json
  - TestStatus: !include schema/test_status.json

/solutions:
  get:
    description: Get list of solutions.
    responses:
      200:
        body:
          application/json:
            schema: Solutions
            example: !include samples/solutions-retrieve.json
  post:
    description: Send source files with solution.
    body:
      application/json:
        schema: Solution
        example: !include samples/solution-new.json
    responses:
      201:
        body:
          application/json:
            schema: SolutionCreateResponse
            example: !include samples/solution_create_response.json
  /{solution_id}:
    get:
      description: Retrieve the solution.
      responses:
        200:
          body:
            application/json:
              schema: Solution
              example: !include samples/solution-retrieve.json
    delete:
      description: Deletes solution from the server.
      responses:
        204:
    /compiler_output:
      get:
        description: Compile the solution and retrieve the compiler output.
        responses:
          200:
            body:
              application/json:
                schema: CompilerOutput
                example: !include samples/compiler_output-retrieve-good.json
                  
          304:
            body:
              application/json:
                schema: CompilerOutput
                example: !include samples/compiler_output-retrieve-error.json
                  
/testcases:
  get:
    description: Returns list of testcases.
    responses:
      200:
        body:
          application/json:
            schema: Testcases
            example: !include samples/testcases-retrieve.json
  post:
    description: |
      Create a test case consisting of the input and expected results.
    body:
      application/json:
        schema: Testcase
        example: !include samples/testcase-new.json
    responses:
      200:
        body:
          application/json:
            schema: TestcaseCreateResponse
            example: !include samples/testcase_create_response.json
              
  /{testcase_id}:
    get:
      description: Get testcase with the given id.
      responses:
        200:
          body:
            application/json:
              schema: Testcase
              example: !include samples/testcase-retrieve.json
    delete:
      description: Deletes the testcase.

/tests:
  get:
    description: List delegated tests.
    responses:
      200:
        body:
          application/json:
            schema: Tests
            example: !include samples/tests-retrieve.json
  post:
    description: Assign test to perform.
    body:
      application/json:
        schema: Test
        example: !include samples/test-new.json
    responses:
      202:
        body:
          application/json:
            schema: TestStatus
            example: !include samples/test_status-new.json
  /{test_id}:
    get:
      description: Returns status of the performed test.
      responses:
        200:
          body:
            application/json:
              schema: TestStatus
              example: !include samples/test_status-retrieve-finished.json
        202:
          body:
            application/json:
              schema: TestStatus
              example: !include samples/test_status-retrieve-pending.json
